name: Análisis de Seguridad Estático (SAST y SCA)

on:
  push:
    branches:
      - master

jobs:
  analisis-seguridad:
    name: Escaneo de Código y Dependencias
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el código del repositorio
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Ejecutar SonarQube Scanner (Análisis de Código)
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Ejecutar Snyk (Análisis de Dependencias)
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test # Analiza vulnerabilidades en paquetes instalados





name: Análisis de Seguridad Dinámico (DAST) Frontend

on:
  push:
    branches:
      - master

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Escaneo DAST con OWASP ZAP
    steps:
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: '[https://pry-bina-front.vercel.app](https://pry-bina-front.vercel.app)'


